[libraries]
# For published releases adjust mpsMajor in build.gradle.kts and use this dependency:
# mps = "com.jetbrains:mps:202x.y"
mps = "com.jetbrains.mps:mps-prerelease:253.28294.10334"
jbr = "com.jetbrains.jdk:jbr_jcef:21.0.6-b895.109"
